# Generated by Django 2.2.12 on 2020-04-09 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import hvad.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='_hvad_query',
            field=hvad.fields.SingleTranslationObject('aldryn_blog.Category', 'aldryn_blog.CategoryTranslation'),
        ),
        migrations.AlterField(
            model_name='allentriesplugin',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='aldryn_blog_allentriesplugin', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='authorsplugin',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='aldryn_blog_authorsplugin', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='master',
            field=hvad.fields.MasterKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aldryn_blog.Category'),
        ),
        migrations.AlterField(
            model_name='latestentriesplugin',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='aldryn_blog_latestentriesplugin', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='coauthors',
            field=models.ManyToManyField(blank=True, related_name='aldryn_blog_coauthors', to=settings.AUTH_USER_MODEL, verbose_name='Co-Authors'),
        ),
        migrations.AlterField(
            model_name='post',
            name='language',
            field=models.CharField(blank=True, choices=[('de', 'German'), ('en', 'English'), ('zh', 'Chinese')], help_text='leave empty to display in all languages', max_length=5, null=True, verbose_name='language'),
        ),
    ]
